apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: DS_PROMETHEUS
    url: http://prometheus.monitoring.svc.cluster.local:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 30s
    version: 1

  - name: Loki
    type: loki
    access: proxy
    uid: DS_LOKI
    url: http://loki.monitoring.svc.cluster.local:3100
    isDefault: false
    editable: false
    jsonData:
      maxLines: 5000
      timeout: 60
      derivedFields:
        - datasourceUid: DS_LOKI
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    version: 1