apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ml-speech-emotion

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - backend-deployment.yaml
  - streamlit-deployment.yaml
  - grafana-external-service.yaml
  - ingress.yaml

images:
  - name: sagerstack/ml-speech-emotion-backend
    newTag: latest
  - name: sagerstack/ml-speech-emotion-streamlit
    newTag: latest
