{
 "title": "App Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{handler!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Request rate by handler (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by(handler) (rate(http_requests_total{handler!=\"/metrics\"}[1m]))"
    }
   ]
  },
  {
   "title": "Request rate by status (5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_requests_total{handler!=\"/metrics\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latency p95 (http_request_duration_seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler!=\"/metrics\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Recent logs (all app)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{namespace=\"ml-speech-emotion\"}"
    }
   ]
  }
 ]
}