{
 "title": "App Logs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "ml-speech-emotion" }
  ]
 },
 "panels": [
  {
   "title": "All namespace logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Backend logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\",container=\"backend\"}"
    }
   ]
  },
  {
   "title": "Streamlit logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\",container=\"streamlit\"}"
    }
   ]
  },
  {
   "title": "Log volume by container (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(container) (count_over_time({namespace=\\\"$namespace\\\"}[1m]))"
    }
   ]
  }
 ]
}