#!/usr/bin/env python3
"""
SageMaker Inference Server Entry Point

This script starts nginx and gunicorn to serve the model.
"""

import multiprocessing
import os
import signal
import subprocess
import sys

# Number of workers defaults to CPU count
MODEL_SERVER_WORKERS = int(os.environ.get('MODEL_SERVER_WORKERS', multiprocessing.cpu_count()))
MODEL_SERVER_TIMEOUT = int(os.environ.get('MODEL_SERVER_TIMEOUT', 60))


def sigterm_handler(nginx_pid, gunicorn_pid):
    """Handle SIGTERM signal for graceful shutdown."""
    try:
        os.kill(nginx_pid, signal.SIGQUIT)
    except OSError:
        pass
    try:
        os.kill(gunicorn_pid, signal.SIGTERM)
    except OSError:
        pass
    sys.exit(0)


def start_server():
    """Start nginx and gunicorn servers."""
    print('Starting the inference server with {} workers.'.format(MODEL_SERVER_WORKERS))

    # Start nginx
    nginx = subprocess.Popen(['nginx', '-c', '/opt/program/nginx.conf'])

    # Start gunicorn
    gunicorn = subprocess.Popen([
        'gunicorn',
        '--timeout', str(MODEL_SERVER_TIMEOUT),
        '-k', 'gevent',
        '-b', 'unix:/tmp/gunicorn.sock',
        '-w', str(MODEL_SERVER_WORKERS),
        'wsgi:app'
    ])

    # Set up signal handler
    signal.signal(signal.SIGTERM, lambda a, b: sigterm_handler(nginx.pid, gunicorn.pid))

    # Wait for child processes
    pids = {nginx.pid, gunicorn.pid}
    while True:
        pid, _ = os.wait()
        if pid in pids:
            break

    sigterm_handler(nginx.pid, gunicorn.pid)
    print('Inference server exiting')


if __name__ == '__main__':
    start_server()
